services:
  server:
    image: "enyalius/fulldev"
    environment:
      #o padrão é 1000 mas se quiser rodar um outro usuário veja o id usando o comando: id -u 
      - WEBAPP_USER_ID=${USER_ID:-1000}
    volumes:
      - ./:/app
    ports:
      - 8080:80
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5052:80
    environment:
      - PMA_ARBITRARY=1
